name: Deploy to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate environment
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Error: SUPABASE_ACCESS_TOKEN is not set"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        run: npm install -g supabase

      - name: Deploy to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_ID: kerhxmwljwhfpcblmlwn
        run: |
          supabase login --access-token $SUPABASE_ACCESS_TOKEN
          supabase link --project-ref $PROJECT_ID
          supabase db push 

      - name: Validate environment
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Error: SUPABASE_ACCESS_TOKEN is not set"
            exit 1
          fi 